
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author esmeldy
 */
public class FormularioGestion extends javax.swing.JFrame {

    /**
     * Creates new form FormularioGestion
     */
    public FormularioGestion() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cod = new javax.swing.JLabel();
        Nombre = new javax.swing.JLabel();
        Cantidad = new javax.swing.JLabel();
        Descripción = new javax.swing.JLabel();
        Cod_producto = new javax.swing.JTextField();
        nom_producto = new javax.swing.JTextField();
        cant_producto = new javax.swing.JTextField();
        Desc_producto = new javax.swing.JTextField();
        bt_Insertar = new javax.swing.JButton();
        bt_buscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_area = new javax.swing.JTextArea();
        listado_producto = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        bt_mostrar = new javax.swing.JButton();
        bt_salir = new javax.swing.JButton();
        bt_clean = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Formulario de Gestión");

        cod.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        cod.setText("Código");

        Nombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Nombre.setText("Nombre");

        Cantidad.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Cantidad.setText("Cantidad");

        Descripción.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Descripción.setText("Descripción");

        Cod_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cod_productoActionPerformed(evt);
            }
        });

        bt_Insertar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_Insertar.setText("Insertar");
        bt_Insertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_InsertarActionPerformed(evt);
            }
        });

        bt_buscar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_buscar.setText("Buscar");
        bt_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_buscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 254, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 67, Short.MAX_VALUE)
        );

        txt_area.setColumns(20);
        txt_area.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txt_area.setRows(5);
        txt_area.setBorder(javax.swing.BorderFactory.createEtchedBorder(null, java.awt.Color.lightGray));
        jScrollPane1.setViewportView(txt_area);

        listado_producto.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        listado_producto.setText("Listado de productos");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        bt_mostrar.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_mostrar.setText("Mostrar");
        bt_mostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_mostrarActionPerformed(evt);
            }
        });

        bt_salir.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        bt_salir.setText("Salir");
        bt_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salirActionPerformed(evt);
            }
        });

        bt_clean.setBackground(new java.awt.Color(204, 255, 255));
        bt_clean.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        bt_clean.setText("Limpiar registros");
        bt_clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cleanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cod, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Nombre)
                            .addComponent(Cantidad)
                            .addComponent(Descripción))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cant_producto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(nom_producto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Cod_producto, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Desc_producto)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(bt_Insertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                        .addComponent(bt_buscar)
                        .addGap(15, 15, 15)))
                .addGap(22, 22, 22)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(listado_producto))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(bt_mostrar)
                                        .addGap(50, 50, 50)
                                        .addComponent(bt_clean)
                                        .addGap(39, 39, 39)))
                                .addComponent(bt_salir))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(78, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 12, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(listado_producto)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(cod)
                                    .addComponent(Cod_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Nombre)
                                    .addComponent(nom_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Cantidad)
                                    .addComponent(cant_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Descripción)
                                    .addComponent(Desc_producto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(bt_Insertar)
                                    .addComponent(bt_buscar)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_mostrar)
                            .addComponent(bt_clean, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_salir))
                        .addGap(13, 13, 13)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Cod_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cod_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Cod_productoActionPerformed

    private void bt_InsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_InsertarActionPerformed
        Productos p = new Productos(Integer.parseInt(Cod_producto.getText()), nom_producto.getText(),
                Integer.parseInt(cant_producto.getText()), Desc_producto.getText());
        String resultado = p.altas();
        txt_area.setText(resultado);
       
    }//GEN-LAST:event_bt_InsertarActionPerformed

    private void bt_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bt_salirActionPerformed

    private void bt_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_buscarActionPerformed
        Productos p = new Productos();
        String a = p.buscar(Cod_producto.getText());
        txt_area.setText(a);
    }//GEN-LAST:event_bt_buscarActionPerformed

    private void bt_mostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_mostrarActionPerformed
        Productos p = new Productos();
        String Mostrar="";
        try {
            Mostrar = p.mostrar();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(FormularioGestion.class.getName()).log(Level.SEVERE, null, ex);
        }
        txt_area.setText(Mostrar);
    }//GEN-LAST:event_bt_mostrarActionPerformed

    private void bt_cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cleanActionPerformed
        txt_area.setText("");
        Cod_producto.setText("");
        nom_producto.setText("");
        cant_producto.setText("");
        Desc_producto.setText("");
        
    }//GEN-LAST:event_bt_cleanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormularioGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormularioGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormularioGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormularioGestion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormularioGestion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Cantidad;
    private javax.swing.JTextField Cod_producto;
    private javax.swing.JTextField Desc_producto;
    private javax.swing.JLabel Descripción;
    private javax.swing.JLabel Nombre;
    private javax.swing.JButton bt_Insertar;
    private javax.swing.JButton bt_buscar;
    private javax.swing.JButton bt_clean;
    private javax.swing.JButton bt_mostrar;
    private javax.swing.JButton bt_salir;
    private javax.swing.JTextField cant_producto;
    private javax.swing.JLabel cod;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel listado_producto;
    private javax.swing.JTextField nom_producto;
    private javax.swing.JTextArea txt_area;
    // End of variables declaration//GEN-END:variables
}
